### ISSUE TITLE
Should not be async by default

### ISSUE THREAD

**Issue by sweeneyapps** [saucelabs/saucectl-run-orb#9]
## Expected Behavior
- when async is false, it should run until completion and output results.

## Actual Behavior
- when async is false, it runs as async, and allows the next step to start before completion.

## Steps to Reproduce the Problem

Using circleCI config.yml version 2.1

  1. set saucelabs/saucectl-run version to 3.1.0
  2. add step to build apk from android project
  3. .sauce/config.yml example here:
 ```
version: 2.1
apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  concurrency: 10
  metadata:
    tags:
      - e2e
    build: app
espresso:
  app: ./app/build/outputs/apk/auth/debug/app-debug.apk
  testApp: ./app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
suites:
  - name: "App"
    testOptions:
      clearPackageData: true
      useTestOrchestrator: true
    emulators:
      - name: "Google Pixel 8 GoogleAPI Emulator"
        platformVersions:
          - "14.0"
 ```
  4. add a step in the job:
 ```
      - saucectl/saucectl-run:
          config-file: .sauce/config.yml
          async: false
          show-console-log: true
```
  5. add a step to run bash script like echo "Hello there"
  6. run the job.
  7. you will notice that the saucectl-run job ran as async.
  8. you will see "Hello there" step executed while saucectl is running in the background (run and forget).

## Specifications

  - Version: 3.1.0
  - Platform: docker image: cimg/android:2023.09

## Logs

At the beginning of the console log, it shows --async, and it shouldn't.
```
saucectl installed: /tmp/tmp.WuajVMplOA/saucectl
Running /tmp/tmp.WuajVMplOA/saucectl run -c .sauce/config-noauth.yml --show-console-log --test-env-silent --async
Running version 0.190.1
```
